---
title: Climate Modeling
author: Dan
date: '2018-09-30'
slug: climate-modeling
categories: []
tags:
  - data-wrangling
  - Time Series Analysis
  - R
description: ''
image: ''
keywords: ''
draft: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      message= F, 
                      warning = F)
```


In climate modeling, predicting future concentrations of various chemicals involves complex dynamic interactions that rely upon expertise in atmospheric chemistry and physics. Dedicated research has developed dynamic models that simulate these future values on various time horizons and provide these datasets for public use. Real-world observational data can be matched to these time series simulations to derive more accurate predictions at particular geographic locations through a process called bias correction. With information that link these chemicals to disease progression, researchers can approximate the future burden of disease. 

This project was an extension of my previous study of time series analysis with environmental health application. This exercise is not to analyze new datasets, only to recreate the methods used in a [recent publication](https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002598#sec014) from international collaborators in the United States, China, and Germany.

## Methods:

### *Overview of Analysis*

The workflow for this analysis involves recreating the methods used in the PLOS Medicine article.

### Resampling Historical Data and Bias Correction of Future Estimates

*"In the bias-correction step, daily ozone observations (daily maximum 8-h average, MDA8) at 778 monitoring sites were first assigned to the fine-scale (0.25° × 0.25°) grid cells. The values of fine-scale observations were determined by the average value of monitoring sites within each grid cell. The fine-scale observations were then resampled to coarse-scale (2.0° × 2.5°, latitude × longitude) using a bilinear interpolation, which enables direct comparisons between observations and historical simulations of the Geophysical Fluid Dynamics Laboratory (GFDL) chemistry-climate model CM3 (GFDL-CM3). In a given 2.0° × 2.5° grid cell, for each of the 12 months, all daily values within the same month in a study period were used to construct a distribution function of daily values in this month. Biases were then identified by comparing the corresponding distribution functions between historical GFDL-CM3 simulations and observations."*

To break down this excerpt into discrete steps:

* Collect simulated and observational meteorological data
* Assign observational data to grid cells
* Resample gridded observational data to an appropriate grid for direct comparison through bilinear interpolation
* Conduct bias correction


### *Data*

#### Collect simulated and observational meteorological data

I will be comparing the observational data to simulated data that assume a certain future climate state described by radiative forcing, an atmospheric property that relates earth's solar absoprtion to the energy radiates back into space. The trend in future greenhouse gas (GHG) concentrations in these assumed future states are called representative concentration pathways (RCP). In this instance, I will compare observational data to simulated data assuming an future radiative forcing that promotes a moderate future GHG trajectory: RCP4.5. 

The simulated historical and future datasets for ozone were collected from the Geophysical Fluid Dynamics Laboratory (GFDL) chemistry-climate model CM3 (GFDL-CM3). The [data portal](http://nomads.gfdl.noaa.gov:8080/DataPortal/cmip5.jsp) provides access to datafrom a range of experiments conducted under the Coupled Model Intercomparison Project (CMIP), an international collaboration to set standards in climate modeling. The simulated data under RCP4.5 in the CM3 experiment is taken from the intersecting [grid cell](http://nomads.gfdl.noaa.gov:8080/DataPortal/getModelExperDataByRealm.jsp?coupled_name=GFDL-CM3&exper_name=rcp45&exper_id=exper_id_5GjzEYkqOW&realiz_id=realiz_id_JDbdw5mxpa) on the data portal. After setting a few parameters, including the time period and the variable of interest ("tro3" for tri-oxygen), the portal produces the dataset for download as a netcdf (.nc) file. This process works for both the historical and future simulated data. 

Observational data was collected from the U.S. Environmental Protection Agency's Clean Air Status and Trends Network (CASTNET). The [data portal](https://java.epa.gov/castnet/clearsession.do) provides and easy click-through menu to filter for the data of interest. Here, I am interested in getting aggregate concentration data (monthly) for Ozone 8-hour daily maximum (MDA8)
for the same time period as the historical simulated data (2011-2015).  

#### Assign observational data to fine-scale grid cells

The observational data is stored as point data with no spatial dimensionality. We will begin by assigning the points to small square grid cells of resolution of 0.25 x 0.25. 

#### Resample gridded observational data to an appropriate grid for direct comparison through bilinear interpolation

To compare observational data with GFDL simulated data, I resample the observational data to the same resolution as the simulated (2, 2.5) using a method called bilinear interpolation. According to the PLOS Medicine article, this allows for direct comparison between the datasets. 

#### Conduct bias correction

I have chosen to use the [climate4R package bundle](https://github.com/SantanderMetGroup) that provides various functions for working with climate data packaged into aptly named packages (loadeR, transformeR, downscaleR, and visualizeR). The bundle is developed by the Santander Meteorology Group at the University of Cantabria in Spain. 


### Conclusions




