---
title: About Dan
author: Dan
date: '2019-01-14'
slug: about-dan
categories: []
tags: []
description: ''
image: ''
keywords: ''
draft: no
---

I want to improve our social systems -social services, public health, environment, safety, transportation- to make them more efficient and impactful for those in need. I like to create and explore new and creative data sources to generate insights and draw conclusions about the world. 

I hope to spend my career investigating the intersection of analytical methods with health and the environment in the pursuit of technological and policy solutions.

My self-education in data science has included the following readings: 

* Introduction to Statistical Learning: With Applications in R (James, Witten, Hastie, and Tibshirani)
* Forecasting: Principles and Practice (Hyndman and Athanasopoulos)
* Statistical Analysis of Network Data in R (Kolaczyk and Csardi)
* A User's Guide to Network Analysis in R (Luke)
* Advanced R (Wickham)
* The R Inferno (Burns)
* Programming Computer Vision with Python (Solem)
* Deep Learning with Python (Chollet)
* Fundamentals of Data Visualization (Wilke)

My projects apply these texts' concepts to interesting questions, often recreating a publication's methods with new datasets with relevant outcomes.
